### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Hetaneko** [jnyfil/localtunnel-loopback#1]
i get this error when i try to connect to sd on colab
`tcp server listening on port: 56415
TypeError: this.info is not a function
    at ClientManager.removeClient (file:///C:/Users/x/AppData/Local/npm-cache/_npx/fe5a604b3e2afe44/node_modules/localtunnel-loopback/lib/ClientManager.js:95:14)
    at Client.<anonymous> (file:///C:/Users/x/AppData/Local/npm-cache/_npx/fe5a604b3e2afe44/node_modules/localtunnel-loopback/lib/ClientManager.js:71:18)
    at Object.onceWrapper (node:events:627:28)
    at Client.emit (node:events:513:28)
    at Client.close (file:///C:/Users/x/AppData/Local/npm-cache/_npx/fe5a604b3e2afe44/node_modules/localtunnel-loopback/lib/Client.js:79:14)
    at Timeout.<anonymous> (file:///C:/Users/x/AppData/Local/npm-cache/_npx/fe5a604b3e2afe44/node_modules/localtunnel-loopback/lib/Client.js:20:18)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
`

**Comment by jnyfil** [comment]
This error has already been fixed and published. 
If you installed it with 'npm install -g localtunnel-loopback', try updating it with 'npm install -g localtunnel-loopback' and restarting.
If it still doesn't work, try removing it with 'npm uninstall -g localtunnel-loopback' and reinstalling it.

**Comment by Hetaneko** [comment]
> This error has already been fixed and published. If you installed it with `npm install -g localtunnel-loopback`. try updating it with `npm update -g localtunnel-loopback` and restarting. If it still doesn't work, try removing it with `npm uninstall -g localtunnel-loopback` and reinstalling it.

reinstalled work but this time it is removing the client after it started to listen
![Untitled](https://user-images.githubusercontent.com/54069666/222874525-e2fa4463-69bd-416e-9178-bc4e27a00e00.png)

**Comment by Hetaneko** [comment]
> This error has already been fixed and published. If you installed it with `npm install -g localtunnel-loopback`. try updating it with `npm update -g localtunnel-loopback` and restarting. If it still doesn't work, try removing it with `npm uninstall -g localtunnel-loopback` and reinstalling it.

reinstalling worked, thanks
